# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Szóstek Fotografia"
subtitle: "Szóstek Fotografia"
author:  "Kamil Szóstek"
header:
 title: "Kamil Szóstek"
 subtitle: "Kliknij na zdjęcie aby je powiększyć"
footer:
 name: "Cześć! Mam na imię Kamil!"
 bio: "Witaj na mojej stronie! Jestem Kamil i fotografia to moje życie. Od kiedy pamiętam fascynowała mnie ta dziedzina oraz uwiecznianie pięknych rzeczy oraz ulotnych momentów aby móc do nich wracać. Jeśli chciałbyś skorzystać z moich usług jestem otwarty na wszelakie współpracę, więc..."
social_urls:
  instagram: "https://www.instagram.com/bacchu.ss/"
