# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Szóstek Forografia"
subtitle: "Szóstek Fotografia"
author:  "Kamil Szóstek"
header:
 title: "Szóstek"
 subtitle: "Fotografia"
footer:
 name: "Cześć! Mam na imię Kamil!"
 bio: "Robienie zdjęć to moja pasja."
social_urls:
  instagram: "https://www.instagram.com/bacchu.ss/"
