# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Szóstek Fotografia"
subtitle: "Szóstek Fotografia"
author:  "Kamil Szóstek"
header:
 title: "Kamil Szóstek"
 subtitle: "Fotografia"
footer:
 name: "Cześć! Mam na imię Kamil!"
 bio: "Robienie zdjęć to moja pasja, a zaczeło się to w 2017 roku. Najlepiej odnajduje się w fotografii portretowej oraz eventowej, lecz żadna dziedzina nie jest mi obca."
social_urls:
  instagram: "https://www.instagram.com/bacchu.ss/"
