# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Szóstek Fotografia"
subtitle: "Szóstek Fotografia"
author:  "Kamil Szóstek"
header:
 title: "Kamil Szóstek"
 subtitle: "Kliknij na zdjęcie aby je powiększyć"
footer:
 name: "Cześć! Mam na imię Kamil!"
 bio: "Robienie zdjęć to moja pasja, a zaczęło się to w 2017 roku. Najlepiej odnajduję się w fotografii portretowej oraz eventowej, lecz żadna dziedzina nie jest mi obca. Jestem również otwarty na wszelakie współpracę, więc..."
social_urls:
  instagram: "https://www.instagram.com/bacchu.ss/"
